global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node_exporter_clients
    static_configs:
      - targets:
          - cloud.greenleafpacific.com:9100
        labels:
          alias: cloud
          company: greenleaf
      - targets:
          - 139.99.155.122:9100
        labels:
          alias: testing
          company: greenleaf
      - targets:
          - 139.99.171.55:9100
        labels:
          alias: new
          company: greenleaf
      - targets:
          - 172.17.0.1:19100
        labels:
          alias: test
          company: my own
      - targets:
          - 64.227.115.196:9100
        labels:
          alias: payroll
          company: rentall
      - targets:
          - 141.94.121.160:9100
        labels:
          alias: howbot
          company: rentall

  - job_name: cadvisor_clients
    static_configs:
      - targets:
          - cloud.greenleafpacific.com:18082
        labels:
          alias: cloud
          company: greenleaf
      - targets:
          - 139.99.155.122:18082
        labels:
          alias: testing
          company: greenleaf
      - targets:
          - 172.17.0.1:19101
        labels:
          alias: test
          company: my own
      - targets:
          - 64.227.115.196:18082
        labels:
          alias: payroll
          company: rentall
      - targets:
          - 141.94.121.160:18082
        labels:
          alias: howbot
          company: rentall

  - job_name: blackbox
    static_configs:
      - targets:
          - blackbox:9115

  - job_name: blackbox_http_services
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - https://greenleafpacific.com
        labels:
          company: greenleaf
          alias: cloud
          stack: greenleafpacificcom
          service: app
          criticality: high
      - targets:
          - https://erp.greenleafpacific.com
        labels:
          company: greenleaf
          alias: cloud
          stack: erpgreenleafpacificcom
          service: frontend
          criticality: critical
      - targets:
          - https://cgi.greenleafpacific.com
        labels:
          company: greenleaf
          alias: cloud
          stack: cgigreenleafpacificcom
          service: app
          criticality: high
      - targets:
          - https://sg.greenleafpacific.com
        labels:
          company: greenleaf
          alias: cloud
          stack: sggreenleafpacificcom
          service: app
          criticality: high
      - targets:
          - https://spa.com.fj
        labels:
          company: greenleaf
          alias: cloud
          stack: spacomfj
          service: app
          criticality: high
      - targets:
          - https://furniture.com.fj
        labels:
          company: greenleaf
          alias: cloud
          stack: furniturecomfj
          service: app
          criticality: high
      - targets:
          - https://bulataxi.com
        labels:
          company: greenleaf
          alias: cloud
          stack: bulataxicom
          service: app
          criticality: high
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
